### ISSUE TITLE
Software Engineer (Web, FullStack)

### ISSUE THREAD

**Issue by robsondealmeida** [Superplayer/jobs#12]
## Descrição da vaga

Oi,

Estamos abrindo uma posição para Senior FullStack Developer na Superplayer & Co. Buscamos uma pessoa apaixonada por aprender, `codar`  que goste de pensar no produto além das linhas de código.

Você será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades nos diversos serviços e aplicações que compõem o Back End e o Front End dos produtos desenvolvidos pela Superplayer & Co. Você vai trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. 🙂

## Responsabilidades

- Pensar, contribuir no planejamento e liderar o desenvolvimento de novas funcionalidades para as aplicações e serviços que compõem os produtos da Superplayer & Co.
- Utilizar as melhores práticas e tecnologias para escrever código em JavaScript (Node.js, ReactJS, Electron), C# (.NET) ou com a melhor linguagem para resolver o problema.
- Desenhar, junto com nosso time de engenheiros, a arquitetura de aplicações de alta escala e alta disponibilidade.
- Cuidar do *deployment* e definição de nossa infraestrutura rodando aplicações com Docker e Kubernetes na AWS e Google Cloud. "*You build it, you run it*".
- Resolver problemas e defeitos em nossos produtos e cuidar para que eles nunca cheguem em ambiente de produção.
- Ajudar nosso time de tecnologia a adotar e utilizar as melhores práticas de desenvolvimento de software para entregar produtos com excelência.
- Definir, junto com todo o time da Superplayer & Co, os caminhos de nossos produtos e nosso processo de desenvolvimento.

## Requisitos

- Paixão em escrever código. Principalmente para as plataformas Node.js ou .NET.
- Ter cursado ou estar cursando algum curso relacionado à informática. Por exemplo: Engenharia de Software, Ciências da Computação, Sistemas de Informação, Processamento de Dados, Análise de Sistemas ou qualquer outra que ensine que 1 + 1 é 0 e vai 1.
- Vivência significativa com desenvolvimento de aplicações web. Tanto Front End quanto Back End.
- Ter a capacidade de desenvolver uma aplicação do 0 (zero). Desde `mkdir` até `./deploy.sh`.
- Domínio de conceitos de OOP (Object Oriented Programming) e conhecimento em Functional Programming.
- Alguma vivência em escrever testes unitários, de integração ou funcionais.
- ♡ Git.
- Conhecimento sobre bancos de dados não relacionais (NoSQL).
- Vivência com rodar aplicações em serviços de Cloud Computing, tais como, Amazon Web Services, Google Cloud Platform ou Windows Azure.
- Capacidade de planejar e desenvolver seu trabalho focando nos objetivos estabelecidos em conjunto com o time.
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.

## Bônus (se você tiver, melhor, se não, tudo bem também)

- Vivência com mais de uma linguagem de programação (de preferência em diferentes plataformas).
- Gostar de resolver as coisas direto no Terminal.
- Alguma vivência ou já ter "brincado" com Docker e/ou Kubernetes.
- Saber o que é Lean Startup e porque isso é importante mesmo sendo um desenvolvedor.
- Paixão por aprender e empreender.
- Tocar algum instrumento ou cantar como um rouxinol. 🐦

## Local

De qualquer lugar desse Brasilzão de Deus!

## Como se candidatar

Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para [jointheband@superplayer.co](mailto:jointheband@superplayer.co) com o assunto Senior FullStack Developer.

**Comment by kivervinicius** [comment]
recebendo currículos ainda?

**Comment by robsondealmeida** [comment]
@kivervinicius claro. Manda pra jointheband@superplayer.co

**Comment by kivervinicius** [comment]
Enviado!

**Comment by kivervinicius** [comment]
Qual prazo para resposta/feedback?

**Comment by robsondealmeida** [comment]
@kivervinicius respondi seu e-mail já 😉
